export const FETCH_SURVEY_LIST = "FETCH_SURVEY_LIST";
export const SURVEY_LIST_RECIEVED = "SURVEY_LIST_RECIEVED";
export const SURVEY_LIST_FAILED = "SURVEY_LIST_FAILED";

export const FETCH_SURVEY_INFO = "FETCH_SURVEY_INFO";
export const SURVEY_INFO_RECIEVED = "SURVEY_INFO_RECIEVED";
export const SURVEY_INFO_FAILED = "SURVEY_INFO_FAILED";

export const UPDATE_SELECTED_OPTION = "UPDATE_SELECTED_OPTION";