export const FETCH_SURVEY_LIST = "FETCH_SURVEY_LIST";
export const SURVEY_LIST_RECIEVED = "SURVEY_LIST_RECIEVED";
export const SURVEY_LIST_FAILED = "SURVEY_LIST_FAILED";

export const FETCH_SURVEY_INFO = "FETCH_SURVEY_INFO";
export const SURVEY_INFO_RECIEVED = "SURVEY_INFO_RECIEVED";
export const SURVEY_INFO_FAILED = "SURVEY_INFO_FAILED";

export const UPDATE_SELECTED_OPTIONS = "UPDATE_SELECTED_OPTIONS";

export const CREATE_SURVEY_COMPLETION = "CREATE_SURVEY_COMPLETION";
export const CREATE_SURVEY_COMPLETION_RECIEVED = "CREATE_SURVEY_COMPLETION_RECIEVED";
export const CREATE_SURVEY_COMPLETION_FAIL = "CREATE_SURVEY_COMPLETION_FAIL";

export const CLEAR_SURVEY_COMPLETION = "CLEAR_SURVEY_COMPLETION";